### ISSUE TITLE
Keycloak bad Aam Digital URL in template

### ISSUE THREAD

**Issue by TheSlimvReal** [Aam-Digital/ndb-setup#29]
In our email template we provide a URL to directly access Aam Digital instance. This is currently hard-coded to `https://{realm}.aam-digital.com` on other domains this URL will be invalid. 
We have provided the correct URL as "Home URL" for the client in Keycloak but this information is not accessible in the template (for all information available in the template see the [Keycloak code](https://github.com/keycloak/keycloak/blob/main/services/src/main/java/org/keycloak/email/freemarker/FreeMarkerEmailTemplateProvider.java#L209).
Currently, I do not see a feasible way to change the URL besides adjusting the template manually (e.g. through the properties) for each domain.

**Comment by TheSlimvReal** [comment]
Theoretically, the "redirect_uri" is present in the url of the login link in the `key` query params. However, this information is base64 encoded and I did not find a way to decode this in the freemaker template.

**Comment by sleidig** [comment]
This is becoming an urgent problem, because we have now added a second server, running under a different domain. Can the realm config define different email templates by configuring a different keycloak theme?

**Comment by tomwwinter** [comment]
There is no easy solution for this. We could do some workarounds:

1. Create a redirect service, wich is linked in email templates

> Link in E-Mail: `aam-digital.com/c/{instance-name}` will redirect to mapped server.

2. Use different E-Mail templates for each production Server and dynamically load the right by realm

> Needs also a Mapping or maybe its possible to use a Realm Property
 
3. migrate all instances to one Domain
