### ISSUE TITLE
Query backend must be reachable for nginx to start

### ISSUE THREAD

**Issue by sleidig** [Aam-Digital/ndb-setup#32]
For the current nginx to start, a reachable query-backend (QUERY_URL) must be defined via the docker-compose env. Otherwise the whole app container fails to start with `nginx: [emerg] host not found in upstream "query" in /etc/nginx/conf.d/default.conf:56`

The ndb-setup and deployer are probably not set up for this yet, so the setup script fails. Ideally, can we make the query-backend optional and see that the nginx starts even without a valid query_url proxy target?

EDIT: if no QUERY_URL is passed in, this does work. i.e. this issue is about updating ndb-setup to smartly provide that only when wanted (--> https://github.com/Aam-Digital/ndb-setup/pull/26/files) 

https://github.com/Aam-Digital/ndb-core/blob/962299e80b69d083b4eabe1fabd8a0c34d8d4daf/build/default.conf#L53-L55

**Comment by sleidig** [comment]
@tomwwinter  is this the same issue you mentioned about the SQS ENV having to be defined?

**Comment by tomwwinter** [comment]
This is already fixed in our ndb-stetup script, problem was a default value for this ENV variable: https://github.com/Aam-Digital/ndb-setup/blob/870560aaba5b2bb1ed72df5dc803ee6948fd2e0a/docker-compose.yml#L16

setting this to localhost, fixed this issue.
